[SERVICE]
    Flush         5
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       nginx
    Reserve_Data true

[OUTPUT]
    Name          loki
    Match         *
    Host          loki
    Port          3100
    Labels        job=fluent-bit
    Label_Keys    $status,$method,$path
    Line_Format   json
