[PARSER]
    Name        nginx
    Format      regex
    Regex       ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+) (?<path>\S+) \S+" (?<status>\d{3}) (?<size>\S+) "(?<referer>[^"]*)" "(?<agent>[^"]*)"(?: "(?<forwarded_for>[^"]*)")?$
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z
